name: Main workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [client, server]
    defaults:
      run:
        working-directory: ./${{ matrix.workdir }}
    steps:
    - uses: actions/checkout@v3
    - name: With ${{ matrix.workdir }}
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
    - run: npm run build

